version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  java-app:
    image: your-java-app
    container_name: java-app
    depends_on:
      - minio
      - dragonfly
      - mysql
    env_file:
      - .env
    environment:
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    secrets:
      - keystore.p12
      - minio_access_key.txt
      - minio_secret_key.txt
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  dragonfly:
    image: dragonflyio/dragonfly
    container_name: dragonfly
    env_file:
      - .env
    environment:
      DRAGONFLY_PASSWORD: ${DRAGONFLY_PASSWORD}
    ports:
      - "${DRAGONFLY_PORT}:${DRAGONFLY_PORT}"
    command: start

  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

secrets:
  keystore.p12:
    external: true
  minio_access_key.txt:
    external: true
  minio_secret_key.txt:
    external: true

volumes:
  mysql-data:
