version: '3.8'
services:
  api:
    image: your-api-image
    secrets:
      - keystore.p12
      - minio_access_key.txt
      - minio_secret_key.txt
    environment:
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
    ports:
      - "8080:8080"

secrets:
  keystore.p12:
    external: true
  minio_access_key.txt:
    external: true
  minio_secret_key.txt:
    external: true
