version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data

  java-app:
    image: your-java-app
    container_name: java-app
    depends_on:
      - minio
      - dragonfly
      - mysql
    env_file:
      - .env
    secrets:
      - keystore.p12
      - minio_access_key.txt
      - minio_secret_key.txt
    ports:
      - "8080:8080"

  dragonfly:
    image: dragonflyio/dragonfly
    container_name: dragonfly
    env_file:
      - .env
    environment:
      DRAGONFLY_PASSWORD: ${DRAGONFLY_PASSWORD}
    ports:
      - "${DRAGONFLY_PORT}:${DRAGONFLY_PORT}"
    command: start

  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql

secrets:
  keystore.p12:
    external: true
  minio_access_key.txt:
    external: true
  minio_secret_key.txt:
    external: true

volumes:
  mysql-data:
