name: Vulnerability Scans
description: Run OSV Scanner, Apisec Scan, Dependency Review, and CodeQL Scan

inputs:
  scan-args:
    description: 'Arguments for the OSV scanner (optional).'
    required: false
    default: '--output=results.sarif'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # OSV Scanner Step
    - name: Run OSV Scanner
      uses: google/osv-scanner-action@v1
      with:
        scan-args: ${{ inputs.scan-args }}

    # Apisec Scan Step
    - name: Run Apisec Scan
      uses: apisec-inc/apisec-run-scan@025432089674a28ba8fb55f8ab06c10215e772ea
      with:
        apisec-project: VAmPI
        sarif-result-file: apisec-results.sarif
        apisec-profile: Master
        apisec-oas: false

    # Dependency Review Step
    - name: Run Dependency Review
      uses: github/dependency-review-action@v2
      with:
        output-file: dependency-review-results.sarif

    # CodeQL Scan Step
    - name: Set up CodeQL
      uses: github/codeql-action/setup-codeql@v2

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
