# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
name: Bearer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '18 7 * * 3'

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  bearer:
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v4

      # Scan code using Bearer CLI
      - name: Run Report
        id: report
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc
        with:
          api-key: ${{ secrets.BEARER_TOKEN }}
          format: sarif
          output: results.sarif
          exit-code: 0

      # Check if SARIF file is valid (ensure 'results' is an array)
      - name: Validate SARIF file
        run: |
          if jq '.runs[0].results == null' results.sarif; then
            echo "No results found, initializing results array."
            jq '.runs[0].results = []' results.sarif > temp.sarif && mv temp.sarif results.sarif
          fi
        continue-on-error: true # This ensures the workflow continues even if validation fails

      # Upload SARIF file
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
